on:
  push:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['24.3']
        elixir: ['1.12.3']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Prepare Development Environment
        run: mix local.rebar --force && mix local.hex --force
        
      - name: mix deps.get
        run: mix deps.get

      - name: mix compile with check
        run: mix compile --all-warnings --warnings-as-errors

      - name: mix foramt with check
        run: mix format --check-formatted

      - name: mix test
      - run: MIX_ENV=test mix test
